export const STUDY_TEST_IDS = {
  screen: 'study-screen',
  catalog: 'study-catalog',
  syllabus: 'study-syllabus',
  syllabusBlock: 'study-syllabus-block',
  continue: 'study-continue',
  search: 'study-search',
  bookmark: 'study-bookmark',
  bookmarkDialog: 'study-bookmark-dialog',
  bookmarkConfirm: 'study-bookmark-confirm',
  bookmarkCancel: 'study-bookmark-cancel',
  saveChip: 'study-save-chip',
  backToCatalog: 'study-back-catalog',
  lessonNav: 'study-lesson-nav',
  lessonTag: 'study-lesson-tag',
  studyObjetivo: 'study-objetivo',
  sectionTitle: 'study-section-title',
  sectionBody: 'study-section-body',
  next: 'study-next',
  previous: 'study-previous',
  progress: 'study-progress',
  deskLesson: 'study-desk-lesson',
  deskPractice: 'study-desk-practice',
  viewSwitch: 'study-view-switch',
  practiceCta: 'study-practice-cta',
  practiceDesk: 'study-practice-desk',
  practiceModeVocab: 'study-practice-mode-vocab',
  practiceModeCompletar: 'study-practice-mode-completar',
  practiceModeTraducir: 'study-practice-mode-traducir',
  practiceModeTransformar: 'study-practice-mode-transformar',
  practiceCard: 'study-practice-card',
  practiceCardFront: 'study-practice-card-front',
  practiceCardBack: 'study-practice-card-back',
  practiceKnew: 'study-practice-knew',
  practiceDidnt: 'study-practice-didnt',
  practiceOption: 'study-practice-option',
  practiceTranslateInput: 'study-practice-translate-input',
  practiceCheck: 'study-practice-check',
  practiceSolution: 'study-practice-solution',
  practiceEmpty: 'study-practice-empty',
  practiceFilterTema: 'study-practice-filter-tema',
  practiceFilterAll: 'study-practice-filter-all',
  practiceBackLesson: 'study-practice-back-lesson',
  practiceNext: 'study-practice-next',
  practiceDirectionEsEn: 'study-practice-direction-es-en',
  practiceDirectionEnEs: 'study-practice-direction-en-es',
  practiceDirectionMixed: 'study-practice-direction-mixed',
  lessonListen: 'study-lesson-listen',
  lessonListenStatus: 'study-lesson-listen-status',
  askTutorPanel: 'study-ask-tutor-panel',
  askTutorInput: 'study-ask-tutor-input',
  askTutorSend: 'study-ask-tutor-send',
  askTutorAnswer: 'study-ask-tutor-answer',
} as const

export const studyInterfaceTexts = {
  screenTitle: 'Estudio',
  catalogTitle: 'English File Beginner',
  backToPracticeLabel: 'Volver a práctica',
  emptyLead: 'Aún no hay lecciones procesadas.',
  emptyHint:
    'El temario lo prepara el curso en estudio/procesado. Elige un tema y abre una lección para leerla.',
  loadingMessage: 'Cargando el temario…',
  indexTitle: 'Índice de lecciones',
  indexHint:
    'Toca una lección para abrirla. Los subtemas del mismo bloque aparecen juntos; cada uno se estudia por separado.',
  continueTitle: 'Continúa desde donde lo dejaste',
  continueOpen: 'abrir →',
  continueOrphanNote: 'Había un marcapáginas, pero esa lección ya no está en el curso.',
  bookmarkPlantLabel: 'Poner marcapáginas en esta lección',
  bookmarkRemoveLabel: 'Quitar marcapáginas de esta lección',
  bookmarkMoveTitle: 'Mover marcapáginas',
  bookmarkMoveBody:
    'Solo puede haber un marcapáginas a la vez. Si continúas, se quitará el actual y se pondrá en esta lección.',
  bookmarkCurrentLabel: 'Marcapáginas actual',
  bookmarkMoveConfirm: 'Sí, mover aquí',
  bookmarkMoveCancel: 'Dejarlo donde está',
  bookmarkOrphanTitle: 'Marcapáginas sin destino',
  bookmarkOrphanBody:
    'Esa lección ya no está en el curso. El marcapáginas quedó sin una página a la que volver.',
  bookmarkOrphanOk: 'Entendido',
  saveChipOn: 'Guardado en este dispositivo',
  saveChipOff: 'Solo esta sesión',
  searchPlaceholder: 'Buscar lección…',
  searchEmpty: 'Ninguna lección coincide con la búsqueda.',
  openLesson: 'abrir →',
  lessonStateDone: 'completada',
  lessonStateCurrent: 'marcapáginas aquí',
  catalogButton: 'Índice',
  lessonTag: (n: number) => `Lección ${n}`,
  lessonPosition: (n: number, total: number) => `Lección ${n} de ${total}`,
  studyLabel: 'Qué estudiar:',
  syllabusTitle: 'Índice',
  previousLabel: 'Anterior',
  nextLabel: 'Siguiente',
  progressLabel: 'Progreso',
  progressValue: (done: number, total: number) => `${done} de ${total}`,
  storageUnavailableHint:
    'El progreso se queda en esta sesión; no se pudo guardar en el dispositivo.',
  deskLessonLabel: 'Temario',
  deskPracticeLabel: 'Prácticas',
  viewSwitchLabel: 'Temario o prácticas',
  practiceCtaLabel: 'Practicar este tema',
  askTutorTitle: 'Pregúntale al profesor',
  askTutorPlaceholder: 'Escribe tu duda sobre esta lección…',
  askTutorSendLabel: 'Preguntar',
  askTutorHint:
    'Respondo solo con el contenido de esta lección, así que nunca invento palabras.',
  answerVocabularyLead: 'En esta lección eso se dice así:',
  answerVocabularyLine: (spanishTerm: string, englishTerm: string) =>
    `${spanishTerm} → ${englishTerm}`,
  answerExampleLabel: 'Ejemplo de la lección:',
  answerPhraseLead:
    'No está en el vocabulario, pero aparece en estas frases de la lección:',
  answerOverviewLead: (objetivo: string) => `Esta lección es para: ${objetivo}`,
  answerOverviewFallbackLead: 'Estas son las frases clave de esta lección:',
  answerUnknownLead: 'Eso no aparece en esta lección. Sí puedes preguntarme por:',
  listenLessonLabel: 'Escuchar lección',
  listenLessonStopLabel: 'Detener lectura',
  listenLessonHint: 'El profesor lee en voz alta el inglés de esta lección.',
  listenLessonProgress: (n: number, total: number) => `Leyendo ${n} de ${total}`,
  backToCatalogLabel: 'Volver al temario',
  backToLessonLabel: 'Volver a la lección',
  filterAllLabel: 'Todo el curso',
  modeVocabLabel: 'Tarjetas',
  modeCompletarLabel: 'Completar',
  modeTraducirLabel: 'Traducir',
  modeTransformarLabel: 'Transformar',
  knewLabel: 'Sabía',
  didntKnowLabel: 'No',
  flipHint: 'Toca para ver el inglés',
  flipHintToEs: 'Toca para ver el español',
  directionGroupLabel: 'Dirección del ejercicio',
  directionEsEnLabel: 'ES → EN',
  directionEnEsLabel: 'EN → ES',
  directionMixedLabel: 'Mixto',
  checkLabel: 'Comprobar',
  nextItemLabel: 'Siguiente',
  emptyModeLead: 'No hay prácticas de este tipo para el filtro actual.',
  emptyModeHint: 'Prueba otro modo o elige Todo el curso.',
  srsCaughtUpLead: 'Por ahora no hay más ejercicios de este tipo.',
  srsCaughtUpHint: 'Los que acertaste vuelven más tarde. Los que fallaste, en un momento.',
  incorrectLabel: 'La solución es:',
  translatePlaceholder: 'Escríbelo en inglés',
  translatePlaceholderToEs: 'Escríbelo en español',
  translatePrompt: 'Traduce al inglés',
  translatePromptToEs: 'Traduce al español',
  blockMeta: (count: number) => `${count} ${count === 1 ? 'subtema' : 'subtemas'}`,
  temaLabels: {
    besingular: 'Verbo be (I, you, he, she, it)',
    classroom: 'Clase y alfabeto',
    beplural: 'Verbo be (we, you, they)',
    nouns: 'Sustantivos y recuerdos',
    foodprices: 'Comida y precios',
    family: 'Familia y adjetivos',
    presentsimple: 'Presente simple',
    time: 'La hora',
    jobs: 'Trabajo y rutina',
    questions: 'Preguntas y cine',
    dates: 'La fecha',
    canlike: 'Can y me gusta',
    prescont: 'Presente continuo',
    invitations: 'Invitaciones',
    therewas: 'There is y pasado de be',
    pastsimple: 'Pasado simple',
    directions: 'Direcciones',
  } as const,
}

export function labelForStudyTema(tema: string): string {
  const labels: Record<string, string> = studyInterfaceTexts.temaLabels
  return labels[tema] ?? tema
}
