export const STUDY_TEST_IDS = {
  screen: 'study-screen',
  syllabus: 'study-syllabus',
  syllabusBlock: 'study-syllabus-block',
  sectionTitle: 'study-section-title',
  sectionBody: 'study-section-body',
  next: 'study-next',
  previous: 'study-previous',
  progress: 'study-progress',
  deskLesson: 'study-desk-lesson',
  deskPractice: 'study-desk-practice',
  practiceCta: 'study-practice-cta',
  practiceDesk: 'study-practice-desk',
  practiceModeVocab: 'study-practice-mode-vocab',
  practiceModeCompletar: 'study-practice-mode-completar',
  practiceModeTraducir: 'study-practice-mode-traducir',
  practiceModeTransformar: 'study-practice-mode-transformar',
  practiceCard: 'study-practice-card',
  practiceCardFront: 'study-practice-card-front',
  practiceCardBack: 'study-practice-card-back',
  practiceKnew: 'study-practice-knew',
  practiceDidnt: 'study-practice-didnt',
  practiceOption: 'study-practice-option',
  practiceTranslateInput: 'study-practice-translate-input',
  practiceCheck: 'study-practice-check',
  practiceSolution: 'study-practice-solution',
  practiceEmpty: 'study-practice-empty',
  practiceFilterTema: 'study-practice-filter-tema',
  practiceFilterAll: 'study-practice-filter-all',
  practiceBackLesson: 'study-practice-back-lesson',
  practiceNext: 'study-practice-next',
} as const

export const studyInterfaceTexts = {
  screenTitle: 'Estudio',
  catalogTitle: 'English File Beginner',
  backToPracticeLabel: 'Volver a práctica',
  emptyLead: 'Aún no hay lecciones procesadas.',
  emptyHint:
    'El temario lo prepara el curso en estudio/procesado. El estudio es lineal: un índice, la lección activa y avance con anterior o siguiente.',
  loadingMessage: 'Cargando el temario…',
  syllabusTitle: 'Índice',
  previousLabel: 'Anterior',
  nextLabel: 'Siguiente',
  progressLabel: 'Progreso',
  progressValue: (done: number, total: number) => `${done} de ${total}`,
  storageUnavailableHint:
    'El progreso se queda en esta sesión; no se pudo guardar en el dispositivo.',
  deskLessonLabel: 'Temario',
  deskPracticeLabel: 'Prácticas',
  practiceCtaLabel: 'Practicar este tema',
  backToLessonLabel: 'Volver a la lección',
  filterAllLabel: 'Todo el curso',
  modeVocabLabel: 'Tarjetas',
  modeCompletarLabel: 'Completar',
  modeTraducirLabel: 'Traducir',
  modeTransformarLabel: 'Transformar',
  knewLabel: 'Sabía',
  didntKnowLabel: 'No',
  flipHint: 'Toca para ver el inglés',
  checkLabel: 'Comprobar',
  nextItemLabel: 'Siguiente',
  emptyModeLead: 'No hay prácticas de este tipo para el filtro actual.',
  emptyModeHint: 'Prueba otro modo o elige Todo el curso.',
  correctLabel: 'Correcto',
  incorrectLabel: 'La solución es:',
  translatePlaceholder: 'Escríbelo en inglés',
  translatePrompt: 'Traduce al inglés',
  blockMeta: (count: number) => `${count} ${count === 1 ? 'subtema' : 'subtemas'}`,
  temaLabels: {
    besingular: 'Verbo be (I, you, he, she, it)',
    classroom: 'Clase y alfabeto',
    beplural: 'Verbo be (we, you, they)',
    nouns: 'Sustantivos y recuerdos',
    foodprices: 'Comida y precios',
    family: 'Familia y adjetivos',
    presentsimple: 'Presente simple',
    time: 'La hora',
    jobs: 'Trabajo y rutina',
    questions: 'Preguntas y cine',
    dates: 'La fecha',
    canlike: 'Can y me gusta',
    prescont: 'Presente continuo',
    invitations: 'Invitaciones',
    therewas: 'There is y pasado de be',
    pastsimple: 'Pasado simple',
    directions: 'Direcciones',
  } as const,
}

export function labelForStudyTema(tema: string): string {
  const labels: Record<string, string> = studyInterfaceTexts.temaLabels
  return labels[tema] ?? tema
}
